# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraMcp < Formula
  desc "MCP server for Jira Cloud"
  homepage "https://github.com/lucasvidela94/jira-mcp"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucasvidela94/jira-mcp/releases/download/v0.1.3/jira-mcp_0.1.3_darwin_amd64.tar.gz"
      sha256 "961c64f8f9b17f761e739d03d21abcb4938cd5d0a73f7f6ac8dbc852caf1e314"

      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucasvidela94/jira-mcp/releases/download/v0.1.3/jira-mcp_0.1.3_darwin_arm64.tar.gz"
      sha256 "805b50ec70f6fbf7b78b42382364ea744f3f46f49ab4ba6ffe9fc7f7c3beeac3"

      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasvidela94/jira-mcp/releases/download/v0.1.3/jira-mcp_0.1.3_linux_amd64.tar.gz"
      sha256 "340cb2155ccce5289a14620ec45007da04660b5533b2a849b5ff0e4a0b5d3d6b"
      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasvidela94/jira-mcp/releases/download/v0.1.3/jira-mcp_0.1.3_linux_arm64.tar.gz"
      sha256 "f540a2740c8de18bbd4b72a1c2d6f7bb8720abe2a0db248fa6ba5b426b6f8115"
      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
  end

  test do
    system "#{bin}/jira-mcp", "--version"
  end
end
