# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraMcp < Formula
  desc "MCP server for Jira Cloud"
  homepage "https://github.com/lucasvidela94/jira-mcp"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucasvidela94/jira-mcp/releases/download/v0.5.0/jira-mcp_0.5.0_darwin_amd64.tar.gz"
      sha256 "6d71ef8dc224bfee98ccf5e2b0c7309bbc656c8cc323e6ec677e9eeaf7dd4a32"

      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucasvidela94/jira-mcp/releases/download/v0.5.0/jira-mcp_0.5.0_darwin_arm64.tar.gz"
      sha256 "004b9a9540ce2c0eb5d5a7c9d245f7e4e092edf565cdda0eeb28783a42fcb4cd"

      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasvidela94/jira-mcp/releases/download/v0.5.0/jira-mcp_0.5.0_linux_amd64.tar.gz"
      sha256 "3870b02df3881c6e668c8d35ee48eee1932356f36d7ecd1052033ac4dbab5b32"
      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasvidela94/jira-mcp/releases/download/v0.5.0/jira-mcp_0.5.0_linux_arm64.tar.gz"
      sha256 "0a292a673b928853262b62effc5f57bde259441c624e2d372ac1f239d77a7b14"
      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
  end

  test do
    system "#{bin}/jira-mcp", "--version"
  end
end
